version: '2'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./vhost:/etc/nginx/conf.d
      - ../server:/var/www/html/server
    links:
      - phpfpm

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: qazasdedc123
    volumes:
      - ./data/mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"

  # redis:
  #   image: redis:3.2.9-alpine
  #   ports:
  #     - "6379:6379"

  phpfpm:
    image: registry.cn-shenzhen.aliyuncs.com/xiaobe/php56:latest
    # build: ./php-fpm5.6
    volumes:
      - ../server:/var/www/html/server
    ports:
      - "9000"
